ФИО:<ins>Кодин Денис Владимирович</ins>     группа: <ins>2</ins>

## Работа с массивами в библиотеке NumPy

In [1]:
import numpy as np

 <b>Задание 1.</b> Задать матрицу $A_{4\times 4}$ случайных чисел любого типа.

In [78]:
a = np.random.randn(4,4) * 10 /10 #np.random.sample
a = a * 100 // 10 
a

array([[-13.,  -1.,   5.,  -2.],
       [ -1.,  -9.,  -4.,   7.],
       [-21.,  -2.,  -6.,  -1.],
       [ 17.,  -5.,  14.,  11.]])

 <b>Задание 2.</b> Случайным образом сгенерировать два целых числа $k$, $l$. Найти минор $M_{k,l}$. 
 
 <ins>Указание:</ins> _Минором $M_{k,l} $ матрицы_ называется определитель матрицы, полученной путём вычеркивания $k$-столбца и $l$-строки
 


In [52]:
np.random.seed(43)

In [97]:
k = np.random.randint(0,3)
j = np.random.randint(0,3)
print('j: {}, k: {}'.format(j, k))

minor_matrix = np.delete(a, j, 0)
minor_matrix = np.delete(minor_matrix, k, 1)

print('minor_matrix: ')
print(minor_matrix)
minor = ((-1)**(k+j)) * np.linalg.det(minor_matrix)

print('Answer:', minor)

j: 0, k: 0
minor_matrix: 
[[-9. -4.  7.]
 [-2. -6. -1.]
 [-5. 14. 11.]]
Answer: -46.0


In [120]:
def solve_minor(a, j, k):
    minor_matrix = np.delete(a, j, 0)
    minor_matrix = np.delete(minor_matrix, k, 1)

    return ((-1)**(k+j)) * np.linalg.det(minor_matrix)


<b>Задание 3.</b> Используя код задания 2, вычислить определитель исходной матрицы $A$ путём разложения её по произвольным строке или столбцу. 

In [129]:
row = 0 # по произвольной строке
deter = 0

for i in range(a.shape[1]):
    deter += a[row, i] * solve_minor(a, row, i)

print('my det: {}, numpy_dets: {}'.format(deter, np.linalg.det(a)))

my det: -10632.0, numpy_dets: -10631.999999999996


<b>Задание 4.</b> Задать массив целых чисел $x$ случайной размерности $d > 2$. Случайным образом определить целое число $n$. Определить сколько и какие элементы в массиве $x$ имеют ту же четность и тот же знак, что и заданное число $n$. 

In [180]:
d = np.random.randint(3,10)
print('dim:', d)

n = np.random.randint(-10,10)
print('random n:', n)
if n % 2 == 0:
    chet = 0
else:
    chet = 1

print("chet: ", chet)
sgn = np.sign(n)
print("sign: ", sgn)
     

a = np.random.randint(low=-10,high=10,size=(d, d))
print('our matrix:')
print(a)

print()
print(20*'-' + 'RESULT' + 20*'-')
print()

filter_true = a[(a % 2 == chet) & (np.sign(a) == sgn)]
print('good element: ', filter_true)
print('count good element: ', filter_true.shape[0])

dim: 4
random n: 2
chet:  0
sign:  1
our matrix:
[[ -4  -7  -1  -4]
 [ -4  -3  -8  -3]
 [-10   3   1  -7]
 [ -4   4  -2   9]]

--------------------RESULT--------------------

good element:  [4]
count good element:  1


<b>Задание 5.</b> Задать два массива вещественных чисел $x$ и $y$ случайной размерности $d > 2$.Получить новый массив $z$, содержащий на $i$-месте целую часть $x_i$, если его дробная часть оказалась больше, чем дробная часть $y_i$ и наоборот. 

Пример входных данных и результата работы программы:

x = [15.14903699  3.77044949 -7.36159982  8.80036869  6.10691581]

y = [ -8.65563977 -12.60192654  15.90580188 -16.63450346  11.83626016]

z = [ -8. 3.  15. 8.  11.]


In [209]:
d = np.random.randint(3,6)
print('dim:', d)
x = np.random.randn(d)*10
y = np.random.randn(d)*10

# test 
#x = np.array([15.14903699,  3.77044949, -7.36159982,  8.80036869,  6.10691581])
#y = np.array([ -8.65563977, -12.60192654,  15.90580188, -16.63450346,  11.83626016])

print('x:', x)
print('y:', y)

rx, dx = np.modf(x)
ry, dy = np.modf(y)

z = [ dx[i] if abs(rx[i]) > abs(ry[i]) else dy[i] for i in range(d)]
print(z)

dim: 3
x: [  4.45201583  -9.26328693 -12.33366339]
y: [-4.62070032  8.71018533  2.57070557]
[-4.0, 8.0, 2.0]


<b>Задание 6.</b> Задать массив натуральных чисел $x$ случайной размерности $d > 2$. Получить массив $y$, содержащий только те элементы из $x$, которые являются степенями двойки.

In [282]:
d = np.random.randint(3, 100)
print('dim:', d)
x = np.random.randint(low=0,high=10,size=(d))
print('x:', x)

y = x[((x & (x-1) == 0) & (x != 0))]
print('y:', y)



dim: 20
x: [2 1 6 3 3 5 1 1 2 7 7 9 9 2 3 4 8 5 4 5]
y: [2 1 1 1 2 2 4 8 4]
