### Дополнительные задания по numpy

ФИО:<ins>Кодин Денис Владимирович</ins>     группа: <ins>2</ins>

In [1]:
import numpy as np

**Задание 1** 

 - Задать матрицу весов W 4 * 4 рандомными вещественными числами;
 - Умножить её на случайный вектор X длиной 4;
 - Выполнить функцию для каждого элемента полученного массива: - 1 / (1+exp(-x*w)) (функцию активации);
 - Применить функуию softmax для результата; 
 - Проверить, что полученный массив дает распределение вероятности по 4м классам (если просуммировать все элементы, то результат будет равен 1 );

In [148]:
# Задать матрицу весов W 4 * 4 рандомнымии вещественными числами;
w = np.random.random([4,4])
print('Weights:')
print(w)
x = np.random.random(4)
print('X:')
print(x)

print()

# Умножить её на случайный массив X длиной 4;
logit = x @ w
print('logit:')
print(logit)

print()

# Выполнить функцию для каждого элемента полученного массива: - 1 / (1+exp(-x*w)) (функцию активации);
sigmoid = (1. / (1. + np.exp(-logit)))
print('sigmoid:')
print(sigmoid)

print()

# Применить функуию softmax для результата;
result = np.exp(sigmoid) / np.sum(np.exp(sigmoid))

print()

print('result(распределение вероятностей):')
print(result)
print('---'*20)
print('Проверка суммированием - ')
print('np.sum(result):',np.sum(result))


Weights:
[[0.24905511 0.21411356 0.5925426  0.80008823]
 [0.02074634 0.16162473 0.13544294 0.39267014]
 [0.87376992 0.38110287 0.74108591 0.46346208]
 [0.04963658 0.21295431 0.07514854 0.9318072 ]]
X:
[0.4237923  0.5309399  0.08029611 0.08871576]

logit:
[0.19112657 0.22604618 0.38920023 0.66743566]

sigmoid:
[0.54763672 0.55627214 0.59609016 0.66092872]


result(распределение вероятностей):
[0.23933303 0.24140872 0.25121508 0.26804316]
------------------------------------------------------------
Проверка суммированием - 
np.sum(result): 1.0


**Задание 2** 

Сравнить скорость выполнения матричного умножения в numpy со скоростью примитивного алгоритма перемножения матриц

In [149]:
def matrixmult (A, B):
    rows_A = len(A)
    cols_A = len(A[0])
    rows_B = len(B)
    cols_B = len(B[0])

    if cols_A != rows_B:
      print("Операцию выполнить невозможно.")
      return
    
    C = [[0 for row in range(cols_B)] for col in range(rows_A)]

    for i in range(rows_A):
        for j in range(cols_B):
            for k in range(cols_A):
                C[i][j] += A[i][k] * B[k][j]
    return C



In [150]:
import time
import random
a = np.random.random([100,100])
b = np.random.random([100,100])

In [151]:

start_time = time.time()
matrixmult(a,b)
print("--- %s seconds три цикла ---" % (time.time() - start_time))

--- 0.2756662368774414 seconds три цикла ---


In [152]:
start_time = time.time()
a@b
print("--- %s seconds операция numpy ---" % (time.time() - start_time))


--- 0.015806913375854492 seconds операция numpy ---
